title: PlateColor
email: yuri2009y@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  自炊生活をもっと楽しく、効率的に。PlateColorは食材管理から献立提案まで、
  あなたの自炊生活をトータルサポートします。
baseurl: ""
url: "https://platecolor.jp"
twitter_username: lis_poire
github_username: lis_poire

# Build settings
remote_theme: jekyll/minima  # themeをremote_themeに変更
plugins:
  - jekyll-feed
  - jekyll-remote-theme    # この行を追加
  - jekyll-seo-tag        # この行を追加

sass:
  style: compressed
  sass_dir: assets/css

# カスタム設定
nav_items:
  - title: 特徴
    url: /features
  - title: レシピ
    url: /recipes
  - title: ブログ
    url: /blog
  - title: About
    url: /about