title: PlateColor
email: yuri2009y@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  自炊生活をもっと楽しく、効率的に。PlateColorは食材管理から献立提案まで、
  あなたの自炊生活をトータルサポートします。
baseurl: ""
url: "https://platecolor.jp"

# カラー設定
colors:
  primary: "#4CAF50"
  accent: "#FF5722"

# SNS設定
social:
  twitter_username: lis_poire
  github_username: YuriYoshid

# ビルド設定
remote_theme: jekyll/minima
plugins:
  - jekyll-feed
  - jekyll-remote-theme   
  - jekyll-seo-tag   
  - jekyll-toc

# TOC設定
toc:
  min_level: 2
  max_level: 3      

# SASS設定
sass:
  style: compressed
  sass_dir: assets/css

# ナビゲーション設定
nav_items:
  - title: 特徴
    url: /features
  - title: レシピ
    url: /recipes
  - title: ブログ
    url: /blog
  - title: About
    url: /about

# ビルド除外設定
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/

# デフォルトのフロントマター設定
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      author: "PlateColor"